language: python
python: 2.7

env:
  matrix:
    - LINT_CHECK="1"
    - TESTS="1"

before_install:
  - psql -c "CREATE DATABASE tests"

addons:
  postgresql: "9.3"

install:
  - pip install --upgrade pip
  - pip install .
  - pip install -r test-requirements.txt
  - pip install -r requirements.txt
  - wget https://raw.githubusercontent.com/Vauxoo/pylint-conf/master/conf/pylint_vauxoo_light.cfg
  - sed --in-place '/^\s*#.*$/d' pylint_vauxoo_light.cfg

script:
  - if [ "${LINT_CHECK}" = "1" ]; then pylint odoo_updates --rcfile=pylint_vauxoo_light.cfg; fi
  - if [ "${TESTS}" = "1" ]; then coverage run setup.py test; fi

after_success:
  if [ "${TESTS}" = "1" ]; then coveralls; fi
